modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="quill"
version="2.2.10"
displayName="Salju's Quill"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
credits="Jusey1, Burack"
authors="Jusey1"
description="Small collection of edits"

[[mixins]]
config="quill.mixins.json"

[[dependencies.quill]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.10]"
    ordering="NONE"
    side="BOTH"
